/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

import back.*;
import javax.swing.JLabel;

/**
 *
 * @author jlope
 */
public class mainWindow extends javax.swing.JFrame {
    private int numPhilosophers;
    private Table table;
    private Philosopher[] philosophers;
    
    private JLabel[] chopsticksUI;
    private JLabel[] philosophersUI;
    private JLabel[] dishes;
    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
        this.numPhilosophers = 5;
        initializeValues();
        
    }

    public void initializeValues(){
        this.table = new Table(numPhilosophers);
        this.philosophers = new Philosopher[numPhilosophers];
        chopsticksUI = new JLabel[numPhilosophers];
            chopsticksUI[0] = imgChopstick1;
            chopsticksUI[1] = imgChopstick2;
            chopsticksUI[2] = imgChopstick3;
            chopsticksUI[3] = imgChopstick4;
            chopsticksUI[4] = imgChopstick5;
        philosophersUI = new JLabel[numPhilosophers];
            philosophersUI[0] = imgPhilosopher1;
            philosophersUI[1] = imgPhilosopher2;
            philosophersUI[2] = imgPhilosopher3;
            philosophersUI[3] = imgPhilosopher4;
            philosophersUI[4] = imgPhilosopher5;
        dishes = new JLabel[numPhilosophers];
            dishes[0] = imgDish1;
            dishes[1] = imgDish1;
            dishes[2] = imgDish1;
            dishes[3] = imgDish1;
            dishes[4] = imgDish1;
    }
    
    public Philosopher createPhilosopher(int index){
        Philosopher newPhilosopher = new Philosopher(table, index);
        return newPhilosopher;
    }
    
    public static void addPhilosopher(Philosopher[] philosophers,Philosopher newPhilosopher){
        philosophers[newPhilosopher.getIndex()] = newPhilosopher;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgDish1 = new javax.swing.JLabel();
        imgDish2 = new javax.swing.JLabel();
        imgDish3 = new javax.swing.JLabel();
        imgDish4 = new javax.swing.JLabel();
        imgDish5 = new javax.swing.JLabel();
        imgPhilosopher1 = new javax.swing.JLabel();
        imgPhilosopher2 = new javax.swing.JLabel();
        imgPhilosopher3 = new javax.swing.JLabel();
        imgPhilosopher4 = new javax.swing.JLabel();
        imgPhilosopher5 = new javax.swing.JLabel();
        imgChopstick1 = new javax.swing.JLabel();
        imgChopstick2 = new javax.swing.JLabel();
        imgChopstick3 = new javax.swing.JLabel();
        imgChopstick4 = new javax.swing.JLabel();
        imgChopstick5 = new javax.swing.JLabel();
        imgTable = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgDish1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dish.png"))); // NOI18N
        jPanel1.add(imgDish1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        imgDish2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dish.png"))); // NOI18N
        jPanel1.add(imgDish2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        imgDish3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dish.png"))); // NOI18N
        jPanel1.add(imgDish3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        imgDish4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dish.png"))); // NOI18N
        jPanel1.add(imgDish4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        imgDish5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dish.png"))); // NOI18N
        jPanel1.add(imgDish5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        imgPhilosopher1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/thinking.gif"))); // NOI18N
        jPanel1.add(imgPhilosopher1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        imgPhilosopher2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/thinking.gif"))); // NOI18N
        jPanel1.add(imgPhilosopher2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        imgPhilosopher3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/thinking.gif"))); // NOI18N
        jPanel1.add(imgPhilosopher3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        imgPhilosopher4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/thinking.gif"))); // NOI18N
        jPanel1.add(imgPhilosopher4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        imgPhilosopher5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/thinking.gif"))); // NOI18N
        jPanel1.add(imgPhilosopher5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        imgChopstick1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chopstick1.png"))); // NOI18N
        jPanel1.add(imgChopstick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        imgChopstick2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chopstick2.png"))); // NOI18N
        jPanel1.add(imgChopstick2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        imgChopstick3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chopstick3.png"))); // NOI18N
        jPanel1.add(imgChopstick3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 365, -1, -1));

        imgChopstick4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chopstick4.png"))); // NOI18N
        jPanel1.add(imgChopstick4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        imgChopstick5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chopstick5.png"))); // NOI18N
        jPanel1.add(imgChopstick5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        imgTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/table.png"))); // NOI18N
        jPanel1.add(imgTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fondo.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        for (int i = 0 ; i < 5 ; i++){
            Philosopher newPhilosopher = createPhilosopher(i);
            addPhilosopher(philosophers, newPhilosopher);
            newPhilosopher.start();
        }
        
        updateInterface();
    }//GEN-LAST:event_btnStartActionPerformed

    public void updateInterface(){
        Thread thread = new Thread (()->{
           while(true){
               //primero recorro los tenedores
            for (int c = 0; c < numPhilosophers ; c++){
                if (table.chopsticks[c].isIsAvailable()){
                    chopsticksUI[c].setVisible(true);
                }else{
                    chopsticksUI[c].setVisible(false); 
                }
            }
            
            //segundo, recorro los filosofos
            for(int p = 0; p < numPhilosophers; p++){
                if(philosophers[p].isIsEating()){
                    philosophersUI[p].setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eating2.gif")));
                }
                else{
                    philosophersUI[p].setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/thinking.gif")));
                }
            }
            
            //tercero, recorro los platos
            for(int d = 0; d < numPhilosophers; d++){
                if(philosophers[d].isIsEating()){
                    dishes[d].setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dinner.png")));
                }
                else{
                    dishes[d].setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dish.png")));
                }
            }
        } 
        });
        thread.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel imgChopstick1;
    private javax.swing.JLabel imgChopstick2;
    private javax.swing.JLabel imgChopstick3;
    private javax.swing.JLabel imgChopstick4;
    private javax.swing.JLabel imgChopstick5;
    private javax.swing.JLabel imgDish1;
    private javax.swing.JLabel imgDish2;
    private javax.swing.JLabel imgDish3;
    private javax.swing.JLabel imgDish4;
    private javax.swing.JLabel imgDish5;
    private javax.swing.JLabel imgPhilosopher1;
    private javax.swing.JLabel imgPhilosopher2;
    private javax.swing.JLabel imgPhilosopher3;
    private javax.swing.JLabel imgPhilosopher4;
    private javax.swing.JLabel imgPhilosopher5;
    private javax.swing.JLabel imgTable;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
